Repository MyNihongo/Moq.Microsoft.Configuration, pull requests merged in 2021-08, with the labels that each got.

#27 publish NuGet in CI
  .github/workflows/ci-build.yml
  .github/workflows/dotnet.yml
Labels: ci

#30 generate unit tests for common types
  .github/dependabot.yml
  .github/workflows/ci-build.yml
  Moq.Microsoft.Configuration.sln
  src/Utils/Helpers/IsExternalInit.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Enums/TestType.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Generators/Base/TestGeneratorBase.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Generators/Base/TestGeneratorEnumerableBase.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Generators/Base/TestGeneratorValueBase.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Generators/ReturnsClassOfEnumerableGenerator.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Generators/ReturnsClassOfValueGenerator.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Generators/ReturnsEnumerableGenerator.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Generators/ReturnsValueGenerator.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Interfaces/IAttributeValueConverter.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Interfaces/IParseMethodConverter.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Interfaces/ITestGenerator.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Models/AttributeValue.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Models/ClassDeclaration.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Models/TypeDetails.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Moq.Microsoft.Configuration.Tests.SourceGenerators.csproj
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Resources/GeneratorConst.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/TestGenerator.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Utils/AttributeValueConverters/CastAttributeValueConverter.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Utils/AttributeValueConverters/DecimalAttributeValueConverter.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Utils/Extensions/GeneratorExecutionContextEx.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Utils/Extensions/StringBuilderEx.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Utils/Extensions/TestTypeEx.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Utils/Extensions/TypeDetailsEx.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Utils/ParseMethodConverters/EnumParseMethodConverter.cs
  tests/Moq.Microsoft.Configuration.Tests.SourceGenerators/Utils/ParseMethodConverters/StringParseMethodConverter.cs
  tests/Moq.Microsoft.Configuration.Tests/ConfigurationSetupTests/ReturnModelShould.cs
  tests/Moq.Microsoft.Configuration.Tests/ConfigurationSetupTests/ReturnsClassClassEnumerableShould.cs
  tests/Moq.Microsoft.Configuration.Tests/ConfigurationSetupTests/ReturnsClassClassValueShould.cs
  tests/Moq.Microsoft.Configuration.Tests/ConfigurationSetupTests/ReturnsClassEnumerableShould.cs
  tests/Moq.Microsoft.Configuration.Tests/ConfigurationSetupTests/ReturnsClassValueShould.cs
  tests/Moq.Microsoft.Configuration.Tests/ConfigurationSetupTests/ReturnsEnumerableShould.cs
  tests/Moq.Microsoft.Configuration.Tests/ConfigurationSetupTests/ReturnsShould.cs
  tests/Moq.Microsoft.Configuration.Tests/ConfigurationSetupTests/ReturnsValueShould.cs
  tests/Moq.Microsoft.Configuration.Tests/EmptyMockConfigurationTests/EmptyMockConfigurationShould.cs
  tests/Moq.Microsoft.Configuration.Tests/MockEmptyTestsBase.cs
  tests/Moq.Microsoft.Configuration.Tests/MockTestsBase.cs
  tests/Moq.Microsoft.Configuration.Tests/Moq.Microsoft.Configuration.Tests.csproj
  tests/Moq.Microsoft.Configuration.Tests/Resources/LongEnum.cs
Labels: improvements

#32 bump to 1.0.5
  src/Moq.Microsoft.Configuration.csproj
Labels: release
